name: anime_scraping
description: Scrapping otakudesu with dart.
version: 1.0.4
# homepage: https://www.example.com
repository: https://github.com/kevinoctavian/anime_scraping
documentation: https://github.com/kevinoctavian/anime_scraping

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  http: ^0.13.5
  html: ^0.15.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
